ScilifelabDataCentre/pathogens-portal

config.yaml
layouts/_default/baseof.html
layouts/index.html
static/css/styles.css

* The table of contents had an issue where setting it to false didn't turn it off. Now fixed.
* Reduced the margins on headings at the top of pages.
* On the homepage, sections that have subpages now automatically have an 'Overview' link added to the top of the accordion, so that the title page can be accessed via a link.

Added 'Overview' link to homepage accordions, fixed ToC bug

---

config.yaml
layouts/index.html

Got rid of the dropdown "Overview" links on the homepage.

Remove 'overview' links on homepage

---

content/english/support_services/resources.md
content/english/support_services/text_and_literature.md
content/svenska/support_services/resources.md
content/svenska/support_services/text_and_literature.md

Changing the titles according to Johans suggestion.
The identifier for the `Resources` section is set to `resource_service` as just `resources` felt like an identifier that may easily mess things up in the future.
No content added inside the sections.
`git mv` seems to have mixed up which file went where, so the diff looks a bit special.
Kind of closes #57

Rename sections to resources and text and literature

---

layouts/partials/footer.html

* Moved SciLifeLab & Elixir logos one above another
* Switched footer to 4-column instead of 5-column layout
* Fixed footer navs to use translated headers instead of hardcoded

Footer tweaks

---

.github/workflows/dockerhub-dev.yml
.github/workflows/dockerhub-latest.yml

I kept getting failure emails because GitHub actions could not push to Docker Hub when running on forks of the repo.
Adding this `if` check should mean that the actions only run on the main fork.

GitHub actions - don't run on forked repos

---

content/english/data_types/imaging_data/data.md
content/english/data_types/protein_data/data.md
content/svenska/data_types/imaging_data/data.md
content/svenska/data_types/protein_data/data.md

The links were all pointing at sequences at EBI.

Updated links and some text for proteins and imaging data types.

---

content/english/support_services/bioinformatics.md
content/svenska/support_services/bioinformatics.md
layouts/partials/footer.html
layouts/partials/navbar.html
static/css/styles.css

* Fix missing alt texts
* Rename Elixir logo on bioinformatics page from nbis logo to elixir
* Increase contrast of links (maybe too much?)

Linus fixing

---

config.yaml
layouts/_default/baseof.html

Hidden by default, shows if you `tab` to select it:
Will be visible by default for browsers with assistive tech turned on. See https://getbootstrap.com/docs/4.0/getting-started/accessibility/#visually-hidden-content

Add screen-reader 'skip to content' link

---

layouts/partials/footer.html
static/css/styles.css

Fixes WAVE accessibility alert about order of headings. There will always be a `<h1>` on the page, so `<h2>` is the next guaranteed heading level.

Make the footer headings h2 level

---

content/english/data_types/health_data/npc-statistics.md
static/css/styles.css

* Put the plots in a wrapper which makes them scroll sideways instead of exceeding the page width
* Added a warning that is only visible on small screens that the user needs to scroll to see the full data.

NPC plots: x-scroll on mobile

---

content/english/data_types/health_data/npc-statistics.md
content/svenska/data_types/health_data/npc-statistics.md

Show the warning about scrolling slightly earlier - at the `lg` breakpoint instead of the `md` breakpoint.

NPC stats - show scroll warning slightly earlier

---

content/english/projects/dashboard.md
content/svenska/projects/dashboard.md
layouts/shortcodes/recent_ten_swe.html

Added table of ten most recent publications to the Swedish language version of the publication statistics page. Added html with Swedish titles and added scope to both html versions. Removed some text from English version now that Swedish version available.

Adding Swedish language recent ten table

---

Dockerfiles/Dockerfile

* Use a more recent Hugo for builds
* Use alpine instead of 1.21-alpine (currently corresponds to the exact same image)
I could not detect any issues during local testing.

Bump klakegg/hugo, use latest alpine

---

.github/workflows/dockerhub-develop.yml
.github/workflows/dockerhub-main.yml

Change the tag names to the more common `latest` and `develop` instead of `latest-latest` and `develop-latest`.
The k8s deployment must be updated with the new tags.

Fix tag names

---

content/english/dashboards/crush_covid.md
content/svenska/dashboards/crush_covid.md

Alert reflects that updates have paused for the summer and will recommence in autumn. They will get in touch when updates resume.

Add alert about data updates to CRUSH dashboard

---

Dockerfiles/Dockerfile

Fix previously used for the RDM Portal and worked correctly. Hopefully the same will work here. Need to test in dev instance first. We can test by clicking the 'see this page' hyperlink in text on the available research projects page

Fix the 8080 redirect error

---

content/english/citation.md
content/svenska/citation.md

In this contribution, I've implemented a 'cite us Swedish' page to provide users with guidelines and resources for citing our work in Swedish publications. This addition enhances the accessibility and clarity of our documentation, catering specifically to Swedish-speaking audiences and facilitating proper citation practices within that context.

Add citation page in Swedish

---

content/english/dashboards/_index.md
content/english/topics/_index.md
content/svenska/dashboards/_index.md
layouts/partials/dashboards.html
layouts/partials/topics.html

In the top navigation bar, add "All dashboards" and "All topics" as sub entry in their respective menu for easy access.
`weight: 1` is specified so it always stays on the top

Add all to dashboard and topics menu

---

layouts/index.html
layouts/topics/single.html

Currently it uses "url" format to retrieve the relevant content for each topic, this dint work well for multi worded tags.
Example, for `infectious diseases` topics, it used `infectious-diseases` to retrieve the contents.
This PR fixes it, so the right format is used to retrieve the contents.

Minor fix for multi-word topics

---

layouts/partials/navbar.html

While testing `pa11y` it complained about elements having same `id`. Though it did not affect the functionality maybe it is better for readability.

Fix redundant IDs

---

layouts/partials/dashboards.html

This enables dashboard cards to show up even if there is no matching entry in the EBI index file yet.
These cards will be at the bottom of the dashboard grid and display a text indicating the absence of entry in EBI index.

FREYA-891 :: Modify script in layouts/partials/dashboards.html

---

content/english/dashboards/RECOVAC.md
content/english/highlights/immunofluorescence.md
content/english/privacy.md
content/svenska/dashboards/RECOVAC.md
content/svenska/privacy.md
layouts/ena_tutorial/single.html
layouts/shortcodes/crush_covid.html
layouts/wastewater/list.html

These are accessibility issues reported by `pa11y`. These are not raised by `wave`, none of this have any affect visually or functionally, but it is a better change code wise.
Issued addressed:
* Duplicate `id` in same page
* Missing `title` for iframes

Fix accessibility reported by pa11y

---

.github/workflows/dockerhub.yml
.github/workflows/link-checker.yml
.github/workflows/trivy-branch.yaml
.github/workflows/trivy-scheduled.yaml

Github decides to use `node v20` for actions from December 2024, so action action methods using older version of node displays warnings about this.
In this PR the relevant methods are updated to use the latest versions.

Update action methods

---

.github/workflows/trivy-branch.yaml
.github/workflows/trivy-scheduled.yaml

`trivy` workflow fails randomly due to too many request error. Trivy knows this and currently trying to fix it, as a work around they have also hosted their DB file in `ECR`. So adding the ecr repo via ENV variable `TRIVY_DB_REPOSITORY ` should reduce the problem if not fixing it.

Trivy workflow fix

---

Dockerfiles/Dockerfile
devbox.json
devbox.lock
layouts/data_table/list.html
layouts/index.html

Update Hugo version from `0.123.7` to `0.139.3` and solve the associated deprecation errors.
Closes [FREYA-1125](https://scilifelab.atlassian.net/browse/FREYA-1125)

Hugo version update

---

content/english/dashboards/wastewater_background.md
content/english/resources/enbiflu.md
content/svenska/dashboards/wastewater_background.md

Linked to Jira issue [FREYA-1179](https://scilifelab.atlassian.net/browse/FREYA-1179)
There was another broken link identified for RSV dashboard which is fixed. Jira issue [FREYA-1205](https://scilifelab.atlassian.net/browse/FREYA-1205)

Fixed dead links related to wastewater dashboards

---

assets/css/styles.css

On smaller viewports, the ToC was overlapping the content. Conditioning the sticky position to larger viewports where the ToC is on the side solves the issue as we don't need sticky ToC on smaller viewports.
Closes [FREYA-1197](https://scilifelab.atlassian.net/browse/FREYA-1197).

FREYA-1197: Wrap ToC sticky behaviour in media query

---

content/english/resources/integrative_outbreak_sim.md

Add an "Outcomes" section to the [PLP Test project page](http://localhost:1313/resources/integrative_outbreak_sim/).
This new section comprises a brief summary of the project outcomes and two visualisations from https://github.com/ScilifelabDataCentre/pathogens-portal-visualisations/pull/114.
Closes [FREYA-1118](https://scilifelab.atlassian.net/browse/FREYA-1118).

FREYA-1118: Add PLP Test reporting section to the project page

---

content/english/resources/integrative_outbreak_sim.md
layouts/partials/footer.html

Add project info and CC-BY 4 license info in footer. The project info text should be same as the one in the [central pathogens portal](https://www.pathogensportal.org/), so it was a copy paste. Just added the institute's abbreviations for some clarity.
This PR also includes a commit to fix the typo's in PR #1216

Add CC license and project info in footer

---

content/english/datasets/_index.md
content/english/datasets/research_group_publications/all.md
content/english/resources/integrative_outbreak_sim.md

`datasets/_index.md` is set with `url`, so visiting that page will redirect to the set URL. So It would be neater to move the _aliases_ to the target to avoid double redirect.
P.S: The `post` field in `/datasets/research_group_publications/all.md` is not used anymore, so removed it.

Move aliases to right file

---

layouts/datasets/query_data.html

Currently, every time someone visits [this](https://www.pathogens.se/datasets/central_portal_data/query_links/) page, 10 requests are made to fetch the number.
Instead of making requests every time, we could cache the numbers so new requests are made only after 6 hours previous visit.

Cache dataset requests

---

layouts/shortcodes/clinmicro_dynamic_content.html

Last updated date is not displaying in [this](https://www.pathogens.se/dashboards/variants_region_uppsala/) dashboard as it is still try to use old (non-existent) blob, so changing it to use the right blob.

Use right blob for clinical micro UU dashboard

---

content/english/datasets/central_portal_data/_index.md
content/english/datasets/research_group_publications/_index.md
layouts/partials/header.html

Similar to the PR in data platform, breadcrumbs code in the portal was also having the code limited to older versions of the `hugo`. In newer version they introduced `.Ancestors` which we can use to neatly implement the breadcrumbs.
The addition of the two new `_index.md` is to avoid adding another exceptional case in the breadcrumbs code.

Make use of Hugo ancestors for breadcrumbs

---

content/english/other_national_portals.md
content/english/updates/PDN_news.md

This PR restructures the national portal page and adds the latest pathogens portal from the Netherlands. It also fixes a typo on the PDN news (removes and extra ) ) 
- Added Netherlands portal
- fixed typo in news
- makes the national pathogens portals the main focus of the national portals page 
Please check links work and read text to ensure that it is correctly edited.
Closes: [FREYA-1384](https://scilifelab.atlassian.net/browse/FREYA-1384?atlOrigin=eyJpIjoiY2Q0Y2UwMDk2NWY4NDhhNmJjYjVjOGJjNjNhNGJjMzIiLCJwIjoiaiJ9)

Freya-1384:Add Netherlands Pathogens Portal

---

pnpm-lock.yaml

This PR patches the following security alert: https://github.com/ScilifelabDataCentre/pathogens-portal/security/dependabot/6
- update `tar-fs` to `3.0.9`
Check that the security alert form Dependabot is gone
Closes: [Dependabot #6](https://github.com/ScilifelabDataCentre/pathogens-portal/security/dependabot/6)

SECURITY-6: Update `tar-fs` version to `3.0.9`
