ScilifelabDataCentre/pathogens-portal

.gitignore

Make git ignore `*~` and `#*#` files.

Make git ignore backup files (~ and #)

---

src/App.vue
src/views/Home.vue

A few updates to the look of the front page. Not intended as a final design, but just something that looks better than the current one. Also updates the name to "hub" instead of "portal".

Updated front page mockup

---

public/index.html

Quick hack to fix the site title.
Fixes #12

Fix site title

---

config.yaml
content/svenska/_index.md
content/svenska/about.md
content/svenska/data_types/compound_and_target_data/_index.md
content/svenska/data_types/genomics_transcriptomics/available_services.md
content/svenska/data_types/genomics_transcriptomics/swedish_data.md
content/svenska/data_types/protein_data/available_services.md
content/svenska/data_types/protein_data/swedish_data.md
content/svenska/data_types/public_health_data/_index.md
content/svenska/data_types/public_health_data/public_health_statistics.md
content/svenska/support_services/_index.md
content/svenska/support_services/general_data_repository.md

Minor updates to the Swedish translation.

Updated Swedish translations

---

content/english/privacy.md
content/svenska/privacy.md

Added the file, but I am unsure how to get it into the site. It must be done in `layouts/partials/footer.html` somehow?

Added Swedish privacy policy.

---

README.md

Added README.

---

layouts/404.html
layouts/_default/baseof.html
layouts/partials/footer.html
layouts/partials/head.html
layouts/partials/navbar.html

x-ref https://github.com/ScilifelabDataCentre/covid-hub/pull/27#discussion_r423618309 for 404 usage.

Language attrs, 404 template

---

config.yaml
content/english/privacy.md
content/svenska/privacy.md
layouts/_default/list.html
layouts/_default/single.html
layouts/partials/footer.html

Mostly related to wiring up the Swedish privacy policy, added in #25

Minor language tweaks & fixes

---

content/svenska/submit.md
content/svenska/support_services/submit_data.md

Remove duplicate submit page on the Swedish translation.

SV: Remove duplicate submit page.

---

config.yaml
layouts/_default/baseof.html
layouts/index.html
layouts/partials/head.html
static/css/styles.css

Added tags that render nice HTML meta tags for sharing:
```html
<meta property="og:title" content="Home" />
<meta property="og:description" content="COVID-19 Data Portal for Swedish Research" />
<meta property="og:type" content="website" />
<meta property="og:url" content="http://localhost:1313/" />
<meta property="og:image" content="http://localhost:1313/img/site_logo/CV19DP_logo_oneliner_SWE.png"/>
<meta property="og:site_name" content="COVID-19 Data Portal Sweden" />
<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:image" content="http://localhost:1313/img/site_logo/CV19DP_logo_oneliner_SWE.png"/>
<meta name="twitter:title" content="Home"/>
<meta name="twitter:description" content="COVID-19 Data Portal for Swedish Research"/>
```

Sharing meta

---

README.md

Wrote some documentation in the repository readme, with contribution instructions.

Readme docs

---

config.yaml

Remove EBI links from homepage

---

README.md
content/english/data_types/genomics_transcriptomics/data.md
content/english/data_types/genomics_transcriptomics/services.md
content/svenska/data_types/genomics_transcriptomics/_index.md
content/svenska/data_types/genomics_transcriptomics/available_services.md
content/svenska/data_types/genomics_transcriptomics/data.md
content/svenska/data_types/genomics_transcriptomics/services.md
content/svenska/data_types/protein_data/_index.md
content/svenska/data_types/protein_data/available_services.md

Some Swedish translations for the Genomics pages, translated by @taborsak
Thank you Fanny!
Phil

Genomics - Swedish translations

---

content/svenska/data_types/imaging_data/_index.md

See discussion in #62 
Fixes #62

Rename "Avbildningsdata" to "Bilddata"

---

content/english/data_types/protein_data/data.md
content/english/data_types/protein_data/guidelines.md
content/english/data_types/protein_data/services.md

With Jochens text additions. Please double check, I did it fast due to meetings under afternoon...

Protein data type update

---

content/english/_index.md
content/english/about.md
content/svenska/_index.md
content/svenska/about.md

Update the info text for the frontpage and the about page.
Fixes #59

Update the info text

---

content/english/data_types/compound_and_target_data/data.md
content/english/data_types/genomics_transcriptomics/data.md
content/english/data_types/imaging_data/data.md
content/english/data_types/protein_data/data.md

Change "Available data" To "Published Data" to avoid confusion when following links (to have the text of the link as the "title" on the page you arrive to)

Change "Available data" To "Published Data"

---

content/english/data_types/genomics_transcriptomics/services.md
content/svenska/data_types/genomics_transcriptomics/services.md

Note: The Swedish translations are just from Google Translate and probably need some work.

Genomics: Add HTGE and Diagnostics Development, cut down NGI text

---

content/english/support_services/bioinformatics.md
content/svenska/submit.md
content/svenska/support_services/bioinformatics.md

Also changing the language a bit in english bioinformatics page

Swedish text for submit and bioinformatics pages

---

content/english/data_types/compound_and_target_data/data.md
content/english/data_types/compound_and_target_data/services.md
content/svenska/data_types/compound_and_target_data/data.md
content/svenska/data_types/compound_and_target_data/services.md

Swedish is only from Google Translate, so needs review.

Added Compound & Target Data content.

---

content/english/support_services/resources.md
content/svenska/support_services/resources.md
static/css/styles.css

Add resource list.
Needs curation and a Swedish translation.

Add Sonjas resource list

---

content/english/support_services/general_data_repository.md
content/svenska/support_services/general_data_repository.md

First versions of English and Swedish texts.

General data repositories

---

layouts/_default/baseof.html
static/css/styles.css

Fixed a new bug that I introduced last night, where there was unintentional spacing in the dropdowns on the homepage.

Minor CSS tweaks & fixes

---

content/english/about.md
content/svenska/about.md

Updates to Swedish and English "about" page, to include short descriptions of organisations behind portal.

Updates to "About" page

---

layouts/partials/footer.html
layouts/partials/head.html

Add Google Analytics to the web page

Add Google Analytics

---

content/english/support_services/submit.md
content/svenska/support_services/submit.md
layouts/partials/navbar.html
static/css/styles.css

New highlighted style for the "Submit Data" button:
Takes the primary pink colour on hover / focus:

Highlight style for 'Submit data' in top nav

---

content/english/support_services/_index.md
content/english/support_services/submit.md
content/svenska/support_services/_index.md
content/svenska/support_services/submit.md
static/css/styles.css

Add 'Support Services' to top navigation

---

static/css/styles.css

Accidentally left this change in #106 after playing with matching the link colour against the logo.
https://github.com/ScilifelabDataCentre/covid-portal/pull/106/files#diff-7962f8c018310ce9bd37011f4b6ce5e3L7-R7
Sorry!

Revert link colour

---

config.yaml
content/english/about.md
content/svenska/about.md
layouts/partials/footer.html

* New section on "About" page describing how the website is built and who to contact if interested in contributing
* New link in footer of every page linking to GitHub
---

Added link to GitHub and new section on About page

---

content/english/support_services/resources.md

Added Covid-19 research funding monitor

Added Covid-19 research funding monitor

---

.github/markdownlint.yml
config.yaml
content/english/data_types/health_data/_index.md
content/english/data_types/health_data/npc-statistics.md

Added first version of NPC statistics page.

---

content/english/data_types/protein_data/data.md
content/svenska/data_types/protein_data/data.md

Link to the European page instead.

Change urls to PDBe

---

content/english/data_types/health_data/_index.md
content/english/data_types/health_data/npc-statistics.md
content/english/data_types/health_data/rut.md
content/svenska/data_types/health_data/npc-statistics.md

Added positive fraction of daily tests.

---

.github/markdownlint.yml
content/english/_index.md
content/english/about.md
content/svenska/_index.md
content/svenska/about.md

Both in English and Swedish. If we deploy this on devel, we can have a look at it and maybe modify it before pushing to productiom.

Added Open positions info, and link to it from home page.

---

container/Dockerfile

Bump Hugo version to 0.78.2 (latest build image)

---

content/english/data_types/health_data/npc-statistics.md
content/svenska/data_types/health_data/npc-statistics.md

Updates about the end of the NPC operations

Add text about the end of NPC

---

container/Dockerfile

To update the Hugo version:
* check which containers are available at https://hub.docker.com/r/klakegg/hugo/
* modify the row in the Dockerfile to match the chosen version

Update Hugo to 0.80.0

---

content/english/projects/dashboard.md
layouts/shortcodes/recent_ten.html

I added the ten most recent table, added text as required (to accompany updates and describe update rate for some visualisations). I also made some small adjustments to the text that I think improve the flow a little bit..

Liane branch

---

data/funded_projects.json

Updated the VR projects that were added for COVID-19 research in June 2021

Added a quotation mark that was missing

---

content/english/data_types/environment/wastewater.md
content/svenska/data_types/environment/wastewater.md

I had to delete </div></div> between the publications to fix position of the items down the page

minor correction on wastewater pages

---

content/english/data_types/environment/wastewater/_index.md
content/svenska/data_types/environment/wastewater/_index.md
content/svenska/data_types/health_data/post_covid.md

Fix link to background on wastewater pages and update date function on Swedish version of postcovid page

wastewater_postcovid_updates

---

content/english/data_types/environment/wastewater/_index.md
layouts/shortcodes/wastewater_map.html
layouts/shortcodes/ww_dynamic_content.html

Reverts ScilifelabDataCentre/covid-portal#610

Revert "Ww page restructuring"

---

layouts/shortcodes/ww_dynamic_content.html

Reverts ScilifelabDataCentre/covid-portal#618

Revert "correct ww dynamic content"

---

layouts/shortcodes/ww_dynamic_content.html

Reverts ScilifelabDataCentre/covid-portal#616

Revert "correct dynamic content code"

---

layouts/shortcodes/ww_dynamic_content.html

Reverts ScilifelabDataCentre/covid-portal#623

Revert "Revert "correct dynamic content code""

---

content/english/data_types/environment/wastewater/_index.md

Reverts ScilifelabDataCentre/covid-portal#625

Revert "Revert wastewater page changes"

---

content/english/data_types/health_data/vaccines.md
content/svenska/data_types/health_data/vaccines.md

Corrected typo on English version and updated 'Swedish' version to reflect recent changes

vaccine pages updates

---

content/english/support_services/tutorial_ena/tutorial_ena_subroute2.md

Different options for uploading files will now open separately

add accordian function to Upload data files section

---

.github/workflows/dockerhub.yml

Publish the generated images to ghcr.io as well.

Publish in ghcr as well

---

content/english/dashboards/vaccines.md
content/svenska/dashboards/vaccines.md

No changes are needed on blob server as a result. Can delete older blob when this is merged

in vaccines page, correct path to blob for timeseries

---

layouts/shortcodes/postcovid_date_modified.html

change to new accompanying diagnosis blob

change blob for alert

---

data/research_projects.json

Fixing link for project: Sociodemografiska faktorer och risken att utveckla långtidssjukdom och komplikationer efter mild respektive svår Covid-19 - Ett fokus på nedsatt arbetsförmåga och utvecklandet av sjukdom i efterförloppet av Covid-19

fix a link in ongoing research projects

---

content/english/highlights/omicron_variant_transition.md

Re-release of a data highlight. Update done in conjunction with Lentini et al.

Lentini dh update

---

content/svenska/dashboards/post_covid.md

Realised we also had a notice about summer updates in Swedish, so removed this too

remove Swedish notice postcovid

---

content/english/datasets/biochemistry.md
content/english/datasets/health.md

Made aware of a few broken links. Assessed all of the available data pages and fixed what did not work

fixing broken links in available data sections

---

content/english/dashboards/vaccines.md
content/svenska/dashboards/vaccines.md

This is a temporary alert to inform users that this page requires an update to align with new data format

Initial alert informing users

---

content/svenska/_index.md
content/svenska/about.md
content/svenska/contact/_index.md
data/available_datasets.json
layouts/partials/navbar.html

* Added available data for January 2023
* Modified navbar section for swedish page

Available data and SV navbar

---

layouts/datasets/single.html
layouts/index.html

Missed to do these changes while changed the menu name, so each category was not listed. This should fix it and the listing should work

Available dataset list fix

---

data/events.json

Standard updates for w11

---

config.yaml
content/english/dashboards/RECOVAC.md
content/english/dashboards/covid_publications.md
content/english/dashboards/crush_covid.md
content/english/dashboards/npc-statistics.md
content/english/dashboards/post_covid.md
content/english/dashboards/serology-statistics.md
content/english/dashboards/symptom_study_sweden.md
content/english/dashboards/vaccines.md
content/english/dashboards/wastewater/introduction.md
layouts/dashboards_topics/list.html
layouts/partials/dashboards.html
layouts/partials/highlights.html

Add and display topics to dashboards, and also DH filtering for topics is fixed

Add topics to dashboards

---

data/available_datasets.json

Review required, the corresponding query file (html) is to be found in Slack chat

Updated data for May

---

data/available_datasets.json

Chores:
- updated available publications data for June, 2023
- Updated available publications data July, 2023

Available data june

---

content/english/dashboards/wastewater/_index.md

Adding enteric viruses tag

---

content/english/_index.md
layouts/index.html
static/css/styles.css

Let me know what you think of the design so far. It's inspired by the News section and I didn't want to spice it up too much, but keep it clean and neat.

Freya 364 show funding and events on the right hand margin

---

content/english/publications/_index.md
content/svenska/publications/_index.md
data/available_datasets.json

Available data updated for September.
Publications database updated to September. Updated the information on the publications pages to show new code for the publications searches

Update to publications and available data

---

layouts/contact/list.html

Need to set up new contact form, as old one is not working now

set up new contact form

---

content/english/dashboards/covid_publications.md
content/svenska/dashboards/covid_publications.md

Update text to show recent developments

Update publication dashboard graph and text

---

data/available_datasets.json

Added around 40 publications and 3 available data entries

Updating available data and publications lists for october

---

data/available_datasets.json

Adding latest available data from November 2023.

Available data dec23

---

layouts/index.html

Leaving it in, but commented out, to benefit a later onboarding task

Remove Christmas message

---

content/english/updates/wastewater_update_gothenburg.md
data/available_datasets.json

Chores:
- added available data December 2023 to json file.

Update available data December 2023

---

content/english/dashboards/variants_region_uppsala.md
content/svenska/dashboards/variants_region_uppsala.md

Expanded the granularity of variant classification, need more space for increased number.

Need more room for variant plots

---

.github/workflows/trivy-scheduled.yaml
.github/workflows/update_ebi_index.yaml
.gitignore
EBI/README.md
EBI/index_json_template.py
EBI/update_index_json.py

Have an Index file that will be read by EBI and set up a github action to update this file.

EBI Index file

---

content/english/dashboards/wastewater/covid_quantification/historic_orebro_umea.md
content/svenska/dashboards/wastewater/covid_quantification/covid_quant_SLU.md
content/svenska/dashboards/wastewater/covid_quantification/historic_orebro_umea.md

Modify `historic_orebro_umea.md` to use plotly data visualisation instead of Vega.

Change data visualisation from Vega to Plotly for Umeå and Örebro page.

---

content/english/dashboards/covid_publications.md
content/english/dashboards/npc-statistics.md
content/english/dashboards/post_covid.md
content/english/dashboards/serology-statistics.md
content/english/dashboards/vaccines.md
content/english/dashboards/wastewater/covid_quantification/covid_quant_KTH.md
content/english/share-data.md
content/english/support.md
layouts/contact/list.html
layouts/events/list.html
layouts/index.html
layouts/partials/dashboards.html
layouts/partials/editorials.html
layouts/partials/highlights.html
static/css/styles.css

Accessibility fix for the following pages
* Homepage
* Contact
* Contribute
* Share data
* Support
* Citation
* Events
* All dashboards

Accessibility fixes

---

content/english/dashboards/wastewater/covid_quantification/historic_stockholm.md
content/svenska/dashboards/wastewater/covid_quantification/historic_stockholm.md

This pull request updates the data visualization from Vega to Plotly for Stockholm wastewater historical data.

Change data visualisation from Vega to Plotly for Stockholm historical data

---

layouts/_default/baseof.html
layouts/partials/head.html
static/js/notices.js

The script reads notices from `https://blobserver.dc.scilifelab.se/blob/freya-notices.json` and displays notices on top.

Adding notices script to display notices on the portal

---

layouts/shortcodes/research_projects_table.html

With this, all Pathogens Portal Accessibility tasks for the English version that have been listed on the confluence page, are resolved.

Accessibility -> (Research Projects)

---

content/english/dashboards/variants_region_uppsala.md
content/svenska/dashboards/variants_region_uppsala.md

Add reference as requested by researcher

add reference from Kaden group

---

content/english/citation.md
content/english/contribute.md
content/english/data-sources.md
content/english/events/_index.md
content/english/share-data.md
content/english/support.md
content/svenska/citation.md
content/svenska/contribute.md
content/svenska/share-data.md
content/svenska/support.md
layouts/index.html
layouts/partials/header.html
layouts/partials/navbar.html
layouts/shortcodes/data_sources.html
static/css/styles.css

The header/navigation bar is re-designed and a data source page is added.

Header re-design and Data source page

---

content/english/dashboards/_index.md
content/svenska/dashboards/_index.md

Needed to update dashboard text to reflect recent changes (done in both languages).

update text related to dashboards

---

.github/pa11y.config
.github/sitemap.xml
.github/workflows/ci-tests.yaml
.github/workflows/dockerhub.yml
.github/workflows/link-checker.yml
.github/workflows/pa11y_test.yaml
.github/workflows/trivy-branch.yaml
.github/workflows/trivy-scheduled.yaml

Setting up a (scheduled) workflow to run `pa11ly` to automatically check for accessibility issues.
Also updating `checkout` version, this is already done in the data platform.

Setup pa11y accessibility check

---

layouts/events/list.html
layouts/index.html

A new blob file is created for all events, it will have a field called `target` which will be used to display the event in the right website

Fetch events from new file

---

data/available_datasets.json

Update on publications and available dataset

---

.github/CODEOWNERS

- Team Freya were already code owners.

FREYA-1150: Add CODEOWNERS file

---

assets/css/styles.css
assets/js/search.js
layouts/search/list.html

As mentioned in [FREYA-1239](https://scilifelab.atlassian.net/jira/software/projects/FREYA/boards/17?assignee=5e7c3fd02e3fce0c33deaed8&selectedIssue=FREYA-1239), there was a minor contrast error. So have made the text colour slightly darker.

Fix search text colour

---

data/available_datasets.json

Contains updates from Oct 2024 to Jan 2025

Publications database and Available dataset update

---

data/available_datasets.json

Update on Publications and Available datasets

---

Dockerfiles/Dockerfile

Good to use the latest version of `hugo` as much as possible.
Tested locally and all looks good.

Update hugo version

---

.github/.gitmessage.txt
CONTRIBUTING/adding_editing_information.md

This PR introduces a structured commit message format to improve consistency and readability across contributions. It includes a commit message template and updates the documentation to guide contributors on using it.
- Added a commit message template in `.github/.gitmessage.txt` to define a structured format for commit messages, including types, scopes, and examples for contributors.
- Updated `CONTRIBUTING/adding_editing_information.md` to include instructions on configuring the commit message template using `git config`. This ensures contributors can easily adopt the standardized format when committing changes.
- This template is the same as data.platform.
Closes: [FREYA-1422](https://scilifelab.atlassian.net/browse/FREYA-1422)

Freya-1422: : Add git commit message template
